name: 'dispatch-single-icu'
on:
  workflow_dispatch:
    inputs:
      icu:
        description: ICU version
        required: true
      rebuild:
        description: rebuild
        required: false
jobs:
  icu:
    runs-on: ${{ matrix.os }}
    name: icu4c
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build icu
        env:
          ICU: ${{ github.event.inputs.icu }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKSPACE: ${{ github.workspace }}
        run: |
          existing_version=$(gh release view icu4c 2>/dev/null | grep -Po $ICU | head -n 1)
          if [ "$ICU" != "$existing_version" ] || [ "x${{github.event.inputs.rebuild}}" = "xtrue" ]; then
            bash src/build-icu4c.sh
            bash src/release-icu4c.sh
          else
            echo "icu4c $ICU build exists"
          fi
